### ISSUE TITLE
Lightness in the plot

### ISSUE THREAD

**Issue by Davide-sd** [nschloe/cplot#20]
Hello,
I'm trying to create color bars in the plot to convey more information to users that are not familiar with this kind of plots (myself included). This is an example:

![newplot(6)](https://user-images.githubusercontent.com/9921777/120978556-e4947380-c774-11eb-8935-bbc726df1756.png)

Looking at the description of this project, we see:

```
The representation is chosen such that

    values around 0 are black,
    values around infinity are white,
    values around +1 are green,
    values around -1 are deep purple,
    values around +i are blue,
    values around -i are orange.
```

Am I correct in saying that the colors are scaled in such a way that white represents the maximum value of the absolute value for the specific case? For example, in the above plot at the top/bottom right corners I get an absolute value of 7.24, so my black and white color bar should display this value instead of infinity...

**Comment by nschloe** [comment]
It's not cut off, true white is only achieved at inifinity. It scales up with arctan, so it may appear perfectly white for values around 10, too. Note that at angle 0, the value is green, not red as in your depiction.

**Comment by Davide-sd** [comment]
Ok, you cleared my doubts!

> Note that at angle 0, the value is green, not red as in your depiction.

Nice catch here. I only looked at the +/- i. Thank you!!!

I think this non-issue can be closed.

**Comment by nschloe** [comment]
Btw, cplot now has colorbar support of its own.

![f](https://user-images.githubusercontent.com/181628/129412331-f60be977-6ad2-476c-947f-843301d19a9c.png)
