### ISSUE TITLE
Wrong visualization with Jupyter Notebook and ipympl

### ISSUE THREAD

**Issue by Davide-sd** [nschloe/cplot#60]
When creating multiple plots inside a Jupyter Notebook with `ipympl` and `%matplotlib widget`, the first plot look ok, the second will be overlay-ed to the first and so on...

```python
%matplotlib widget
import numpy as np
import cplot
```

```python
cplot.plot(
    lambda z: np.sin(z**3) / z,
    (-2, 2, 400),
    (-2, 2, 400),
).show()
```
![Figure 1(1)](https://user-images.githubusercontent.com/9921777/154728674-272f23fa-a4cc-47ac-acd4-6a570a93a06a.png)

```python
cplot.plot(
    lambda z: z**6 + 1,
    (-2, 2, 400),
    (-2, 2, 400),
).show()
```
![Figure 1(2)](https://user-images.githubusercontent.com/9921777/154728731-8091e01e-78be-4431-ba3f-3995f384cde0.png)

**Comment by nschloe** [comment]
I think that's normal mpl behavior, at least cplot doesn't do anything special. (I don't think.)
