### ISSUE TITLE
Blurry plot when exporting

### ISSUE THREAD

**Issue by TimeTravelPenguin** [nschloe/cplot#65]
I am not sure if this is an issue per se, but I noticed that plots are blurry when exporting to higher resolution images or when exported to vector format such as SVG.

For example, 
```py
plt.savefig("cplot.svg", format="svg")
```
Works fine on simple matplotlib plots. Vector graphics still appear to be rasterised, and I am not sure if there is a supported way to produce higher-resolution images.

**Comment by nschloe** [comment]
This definitely needs a full example.

**Comment by TimeTravelPenguin** [comment]
Here is my process:

```py
def f(z):
    return np.sin(z*z)*np.cos(1/z)

yrange = (-2, 2, 500)

p = cplot.plot(f, (-2, 2, 500), (-2, 2, 500))

p.savefig("cplot.svg", format="svg")

# This simply converts the SVG to PNG via Inkscape -- no issues here
subprocess.run("inkscape cplot.svg -e cplot.png -w 1000 -b white")

p.show()
```

This will produce the expected plot and output the SVG. Then, I convert via Inkscape to PNG. In both the SVG and PNG version, the hues and contours appear blurry. Note that here I am exporting to a resolution where the width = 1000px.

This is the PNG:

![cplot](https://user-images.githubusercontent.com/35803538/183071169-f0387566-007f-4ac4-b10d-f8b77fa3537d.png)

Here is the same functions with the xy range in -0.5 to 0.5:

![cplot](https://user-images.githubusercontent.com/35803538/183071420-d5761470-dd39-48ce-9e4c-5a644a178dc5.png)

**Comment by TimeTravelPenguin** [comment]
Here is a new, more visible example;

I modified the prior code to have
```py
p.savefig("cplot.png", format="png", dpi=300)
```
(I also removed the Inkscape conversion)
This is the result:

![cplot](https://user-images.githubusercontent.com/35803538/183073759-61786908-b3ab-40ff-ab1f-ce3821383b0f.png)

If you open this image in your browser, everything looks nice, but the plot itself looks rather blurry.

**Comment by nschloe** [comment]
What exactly is blurry? The area around the essential singularity?

**Comment by TimeTravelPenguin** [comment]
Well, everything in the plot, if I am not mistaken. For example, the contours appear rather fuzzy/feathered, as if it has lost resolution due to upscaling. The whole plot looks upscaled rather than being output at the requested DPI/resolution. 

Here is an example by comparison:

```py
import matplotlib.pyplot as plt

def f(z):
    return np.sin(z*z)*np.cos(1/z)

x = np.linspace(-0.25,0.25,500)
plt.plot(x, f(x))

plt.savefig("cplot.png", format="png", dpi=300)
plt.show()
```

This produces a nice, large image with well-defined lines. They are not fuzzy/blurry, as it seems they are rasterised at the required size, rather than being an upscaling, which is what I would have a guess as to what is happening above. This is the image the code produces:

![cplot](https://user-images.githubusercontent.com/35803538/183079175-c5fa7410-985b-4b05-ba3d-d46df4515ad9.png)

Comparing this and my last example side-by-side should show what I mean.

**Comment by nschloe** [comment]
I still don't understand. Everything is blurry? No. I don't see a difference between the blue line in the 1D plot and any line in the cplot.

**Comment by TimeTravelPenguin** [comment]
Ah, perhaps I am mistaken. Upon closer inspection (literally face to my monitor) I think I see the confusion. Take the following region:

![image](https://user-images.githubusercontent.com/35803538/183080755-55002e21-1aa6-4a99-8f15-fa8e3f576d69.png)

They do now look well drawn correctly. I feel that perhaps I mistook them because they looked thicker than I expected. 

Is it at all possible to format line width (the `lw` arg) as you would in matplotlib?

**Comment by nschloe** [comment]
You can't yet, but it's possible to add such functionality. You wouldn't be able to change the color of course.

**Comment by nschloe** [comment]
What properties would you want to change?

**Comment by TimeTravelPenguin** [comment]
I see. Colour isn't an issue for me. It looks pretty and functions well. The main issue I feel is that the thick contour lines (especially in denser regions) look blurry when wanting to output to higher resolutions. So, I would guess that to mitigate this "illusion" would be to adjust the contour line thickness and perhaps the number of contour lines (which I think is already a feature?)

**Comment by nschloe** [comment]
>  perhaps the number of contour lines (which I think is already a feature?)

You can explictly specify the where abs contours are draw, or specify an exponentiation base. (`2` is the default, i.e., lines at ..., 1/4, 1/2, 1, 2, 4,...).

```python
contours_abs: float | ArrayLike | None = 2,
```

> adjust the contour line thickness 

This isn't possible yet.

**Comment by nschloe** [comment]
As a side note, I wouldn't much worry about overlapping lines. You're looking at an essential singularity, and _everything_ happens there. You'll never not have overlapping lines. It's a feature that the area is crazy.

**Comment by TimeTravelPenguin** [comment]
A quick update:

I wanted to know if changing the contour width would resolve my issue of the "illusion". After some looking into matplotlib's API, I made the following adjustment to my code:

```py
import matplotlib as mpl

# ...code...

mpl.rc("lines", linewidth=.8)
p = cplot.plot(f, xrange, yrange, contours_abs = 1.5)
```
The [rc](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.rc.html) function allows me to hack in the change. Here is the result:

![cplot](https://user-images.githubusercontent.com/35803538/183092722-5cd57a6a-a3aa-4656-9f3e-fdbe27de800d.png)

I believe it would be beneficial to allow the use of args/kwargs for things like this, since the plot function should allow use of the matplotlib API -- or at least, to some degree. Though, I am not well-versed in the codebase and do not want to criticise anyone work. Especially since the library is well deserved of praise.

But yes, my poking into hacking a solution confirms that the contour line thickness was indeed my issue. The default line thickness is 1.5, according to matplotlib. I set it to 0.8 and get a more preferred result (personally). Though, I have not played with any other styling choices which would certainly have some effect to the illusion.
