### ISSUE TITLE
In _riemann_sphere.py file, riemann_sphere is not working.

### ISSUE THREAD

**Issue by RusMermaid** [nschloe/cplot#69]
I tried downloading same python libraries that cplot uses:

-     import meshzoo (after checking, seems fine)
-     import pyvista as pv (after checking, seems to contain errors)
-     import vtk (after checking, seems to contain errors)

Errors in using it in Windows 7/10 and MAC OS.

Other parts of **cplot** is _well_ coded with no bugs.
_Thank you!_ _Hope you fix it!_

**Comment by nschloe** [comment]
pyvista and vtk and not cplots responsability.

**Comment by RusMermaid** [comment]
Riemann sphere function - test FAIL
<img width="1081" alt="Screenshot 2022-10-08 at 17 14 56" src="https://user-images.githubusercontent.com/92940400/194711992-52c60597-5291-46c5-8be1-1818aeca094b.png">

**Comment by nschloe** [comment]
When posting code, never post screenshots. They can't be copy-pasted.

**Comment by RusMermaid** [comment]
Ok, but  the test failed

**Comment by nschloe** [comment]
I cannot reproduce the bug. You probably have a problem with VTK or pyvista.

**Comment by nschloe** [comment]
No. Best get back to VTK or pyvista folks.
